// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList.App.Data.Context;

#nullable disable

namespace ToDoList.App.Migrations
{
	[DbContext(typeof(TaskContext))]
	[Migration("20230526160100_ChangePropertyIsCompletedToCompletedAt")]
	partial class ChangePropertyIsCompletedToCompletedAt
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "6.0.16")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

			modelBuilder.Entity("ToDoList.Models.TaskModel", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<DateTime?>("CompletedAt")
						.HasColumnType("datetime2");

					b.Property<DateTime>("CreatedAt")
						.ValueGeneratedOnAdd()
						.HasColumnType("datetime2")
						.HasDefaultValueSql("GETDATE()");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("varchar(100)");

					b.Property<string>("Title")
						.IsRequired()
						.HasColumnType("varchar(20)");

					b.HasKey("Id");

					b.ToTable("Tasks");
				});
#pragma warning restore 612, 618
		}
	}
}
